development:
  clients:
    default:
      database: mongoid_dev
      hosts:
        - db:27017
  options:
    raise_not_found_error: false
    log_level: debug
production:
  clients:
    default:
      database: mongoid_prod
      hosts:
        - <%= "#{ENV['DB_ADDRESS']}:27017" %>
test:
  clients:
    default:
      database: mongoid_test
      hosts:
        - localhost:27017
