version: '3.9'
services:
  db:
    build: database
    restart: always
  db-seed:
    build: 
      context: database/seed
      dockerfile: Dockerfile.dev
    links:
      - db
  app-back:
    build: backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/home/sinatra/app
  app-front:
    build: frontend
    ports:
      - '80:3000'
    volumes:
      - ./frontend:/home/react/app
    environment:
      - REACT_APP_BACK_ADDRESS=http://localhost:4000/graphql
