version: '3.9'
services:
  db:
    build: database
    restart: always
    ports:
      - '27017:27017'
  db-seed:
    build: 
      context: database/seed
      dockerfile: Dockerfile.dev
    links:
      - db
  app-back:
    build: backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/home/app
      - /home/app/.bundle/
      - /home/app/coverage/
      - /home/app/spec/
  app-front:
    build: frontend
    ports:
      - '80:3000'
    volumes:
      - ./frontend/public:/home/app/public
      - ./frontend/src:/home/app/src
    environment:
      - REACT_APP_BACK_ADDRESS=http://localhost:4000/graphql