version: '3.9'
services:
  db:
    build: database
    restart: always
    ports:
      - '27017:27017'
  db-seed:
    build: 
      context: database/seed
      dockerfile: Dockerfile.dev
    links:
      - db
  app-back:
    build: 
      context: backend
      dockerfile: Dockerfile.ci
    ports:
      - '4000:4000'
  app-front:
    build: 
      context: frontend
      dockerfile: Dockerfile.ci
    ports:
      - '80:3000'
    environment:
      - REACT_APP_BACK_ADDRESS=http://localhost:4000/graphql