FROM ruby:alpine

WORKDIR /home/app
COPY Gemfile* ./
RUN apk add --update build-base
RUN bundle config set frozen 'true' && bundle config set without 'test' && \
bundle install --jobs $(nproc) --quiet
COPY . .

CMD ["bundle", "exec", "puma", "-C", "puma.rb"]