# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bcrypt'
gem 'graphql'
gem 'jwt_sessions'
gem 'mongoid'
gem 'puma'
gem 'rack-contrib'
gem 'rubocop', require: false
gem 'search_object_graphql'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-cors'
gem 'sysrandom'
group :test do
  gem 'codecov'
  gem 'database_cleaner-mongoid'
  gem 'factory_bot'
  gem 'mongoid-rspec'
  gem 'simplecov'
  gem 'simplecov-lcov'
end
