version: 2.1

orbs:
  codecov: codecov/codecov@1.2.5

jobs:
  node-tests:
    working_directory: ~/automated-light/frontend
    docker:
      - image: cimg/node:16.6.0
    steps:
      - checkout:
          path: ~/automated-light
      - run:
          name: install dependencies and run tests
          command: |
            yarn install
            yarn jest --coverage
      - codecov/upload:
          file: "coverage/coverage-final.json"

  ruby-tests:
    working_directory: ~/automated-light/backend
    docker:
      - image: cimg/ruby:3.0.0
    steps:
      - checkout:
          path: ~/automated-light
      - run:
          name: run tests
          command: |
            bundle install
            ./run_unit_tests.sh

  plan-apply:
    working_directory: ~/automated-light/infra
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout:
          path: ~/automated-light
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  dev:
    jobs:
      - node-tests
      - ruby-tests
  # prod:
  #   jobs:
  #     - plan-apply
  #     - hold-apply:
  #         type: approval
  #         requires:
  #           - plan-apply
  #     - apply:
  #         requires:
  #           - hold-apply
  #     - plan-destroy:
  #         requires:
  #           - apply
  #     - hold-destroy:
  #         type: approval
  #         requires:
  #           - plan-destroy
  #     - destroy:
  #         requires:
  #           - hold-destroy
